name: Build

on:
  push:
    branches:
      - 'master'
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: cstr-runner

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup VS environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Setup VCPKG + Ninja
        shell: pwsh
        run: |
          $env:VCPKG_ROOT = "C:/Tools/vcpkg"
          $env:VCPKG_FEATURE_FLAGS = "manifests,binarycaching"
          $env:VCPKG_BINARY_SOURCES = "clear;files,C:/Tools/vcpkg/packages,readwrite"
          $env:PATH += ";C:/Tools"

          ninja --version

      # ---------------- DEBUG ----------------

      - name: Configure (Debug)
        shell: pwsh
        run: |
          cmake -S . -B _build/x64-Debug `
            -G Ninja `
            -DCMAKE_BUILD_TYPE=Debug `
            -DCMAKE_MAKE_PROGRAM="C:/Tools/ninja.exe" `
            -DCMAKE_TOOLCHAIN_FILE="C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET=x64-windows-zhm `
            -DVCPKG_OVERLAY_TRIPLETS=cmake/vcpkg-overlays `
            -DVCPKG_BINARY_SOURCES="clear;files,C:/Tools/vcpkg/packages,readwrite"

      - name: Build (Debug)
        shell: pwsh
        run: cmake --build _build/x64-Debug -j12

      - name: Install (Debug)
        shell: pwsh
        run: cmake --install _build/x64-Debug

      # ---------------- RELEASE ----------------

      - name: Configure (Release)
        shell: pwsh
        run: |
          cmake -S . -B _build/x64-Release `
            -G Ninja `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_MAKE_PROGRAM="C:/Tools/ninja.exe" `
            -DCMAKE_TOOLCHAIN_FILE="C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake" `
            -DVCPKG_TARGET_TRIPLET=x64-windows-zhm `
            -DVCPKG_OVERLAY_TRIPLETS=cmake/vcpkg-overlays `
            -DVCPKG_BINARY_SOURCES="clear;files,C:/Tools/vcpkg/packages,readwrite"

      - name: Build (Release)
        shell: pwsh
        run: cmake --build _build/x64-Release -j12

      - name: Install (Release)
        shell: pwsh
        run: cmake --install _build/x64-Release
