name: Build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: cstr-runner

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      # 🔥 VCPKG CACHE
      - name: Cache vcpkg
        uses: actions/cache@v4
        with:
          path: |
            C:/Tools/vcpkg/installed
            C:/Tools/vcpkg/packages
            C:/Tools/vcpkg/buildtrees
          key: vcpkg-${{ runner.os }}-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            vcpkg-${{ runner.os }}-

      # 🔥 ENV
      - name: Setup VCPKG env
        shell: pwsh
        run: |
          $env:VCPKG_ROOT = "C:/Tools/vcpkg"
          $env:VCPKG_DEFAULT_TRIPLET = "x64-windows"
          $env:VCPKG_FEATURE_FLAGS = "manifests,binarycaching"
          $env:VCPKG_BINARY_SOURCES = "clear;files,C:/Tools/vcpkg/packages,readwrite"

          echo "VCPKG_ROOT=$env:VCPKG_ROOT" >> $env:GITHUB_ENV
          echo "VCPKG_DEFAULT_TRIPLET=$env:VCPKG_DEFAULT_TRIPLET" >> $env:GITHUB_ENV
          echo "VCPKG_FEATURE_FLAGS=$env:VCPKG_FEATURE_FLAGS" >> $env:GITHUB_ENV
          echo "VCPKG_BINARY_SOURCES=$env:VCPKG_BINARY_SOURCES" >> $env:GITHUB_ENV

      # 🔥 CONFIGURE
      - name: Configure
        shell: pwsh
        run: |
          cmake -S . -B _build `
            -G Ninja `
            -DCMAKE_BUILD_TYPE=Debug `
            -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"

      # 🔥 BUILD
      - name: Build
        shell: pwsh
        run: cmake --build _build -j12

      - name: Install
        shell: pwsh
        run: cmake --install _build
